description = '''


4. "Demarcated Nation Apparatus"
    I use an FSM to make my coffee every morning.
    These numbers are in base three.
'''

length = 19

matches = [
    '0',
    '2',
    '11',
    '20',
    '22',
    '101',
    '110',
    '112',
    '121',
    '200',
    '202',
    '211',
    '220',
    '222',
    '1001',
    '1010',
    '1012',
    '1021',
    '1100',
    '1102',
    '10222001201111',
    '122021022100212',
]

nonmatches = [
    '1',
    '10',
    '12',
    '21',
    '100',
    '102',
    '111',
    '120',
    '122',
    '201',
    '210',
    '212',
    '221',
    '1000',
    '1002',
    '1011',
    '1020',
    '1022',
    '1101',
    '1110',
    '20122121200002',
    '120100220001022',
]
