description = '''


3. "Parity"
    This one's supposed to be impossible in the general case.
    The tests will enforce a solution for the general case.
'''

length = 12

matches = [
    '<>',
    '<<>>',
    '<><>',
    '<<><>>',
    '<<<<>>>>',
    '<<<>>><>',
    '<<><><<>>>',
    '<><<<><>>>',
    '<<<><><>>>',
    '<<<<<>>><>>>',
    '<<<<<<>>>>>>',
    '<<<<<<<>>>>>>>',
    '<<<>><><<<>>>>',
    '<<<<<<<<<<>>>>>>>>>>',
    '<<<<<<<<<<>>>>>>>>>><>',
    '<><<<>><<>>><<<<>><>>>',
    '<<><><><<<<<><<>>>>>><>>',
    '<<<<><>>><><><>><><><><>',
    '<<>><<>><<>><<<<<<<>>>>><>>>',
    '<<<<<<>>>>>><<<<<<<>>><>>>>>',
    '<<<<>><><>>><<><<>><<<<>>><>>>',
    '<<<><<>><<<>><<<>>><>>>><<<>><>>',
    '<><<><><><<<>>><<<>><>>><<<<><>>>>',
    '<<<<<<>>><>><><><>><>><<<>><><<<>>>>',
    '<<<>><><>><><<><><<<>>>><<<>>><<<><<>>>><><<<>>>',
]

nonmatches = [
    '<',
    '>',
    '<>>',
    '>><>>',
    '<><><<',
    '<<>>><>',
    '<<>>>>><',
    '>><>>>><<',
    '<>><<>><><<<<>>><<',
    '<<>>>>><>><<>><<><<',
    '>>>>><><><><<<>>><>>',
    '><><<<><><>>>>>><<><<',
    '<<<<<><<<><>><>>><>>>><>>>',
    '>>>><>>><><><<<<<>>><>><<><>>><><<>',
    '<>><><>><>><<><>><>>><><>>><><>><><>><',
    '<<<><>>>>><<><<><><<<<>>><<<>>>>>>><>>>',
    '><<>><<<<><><<<><>><<>><<><>>><>>>>>><<>',
    '>>><<<<<<<<<<>>>><<<><<><>><<<><><><<<<>>',
    '<<><>><<>><>>>>><>><><<><>>><<<<<><>><<<<><>',
    '<>><<<><<><<<<<>>><><<<<<<<><><<>><><><<>>>>',
    '><><<<>>><<><<><>>><<<<>><>><><<>>><><<><<<<',
    '><><<<<><<<<<>><<><<><>>>><><<><><><>><<<><><',
    '>>><<>>><><<<<><><><<<<>>>><<<>>><>><<<<<<<<<>',
    '<>><><>>><<>>><>>><>>><<<<>>>><>>><<<<<>><>><>><',
    '<>>>><<<><>><<><<<><<<><>>>>>><>>><>>>>><<<><<<>',
]
