/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_canvas_free(a: number): void;
export function canvas_new(a: number, b: number): number;
export function canvas_new_chall(): number;
export function canvas_render(a: number): void;
export function canvas_get_pix_buf(a: number): number;
export function canvas_width(a: number): number;
export function canvas_height(a: number): number;
export function canvas_canvas_height(a: number): number;
export function canvas_canvas_width(a: number): number;
export function canvas_box_at(a: number, b: number, c: number, d: number): void;
export function canvas_clear_pipe(a: number, b: number, c: number): void;
export function canvas_add_connection(a: number, b: number, c: number, d: number): number;
export function canvas_remove_connection(a: number, b: number, c: number, d: number): number;
export function canvas_game_won(a: number): number;
export function canvas_gen_filled_board(a: number, b: number): number;
export function canvas_clear_all_flows(a: number): void;
export function canvas_gen_new_board(a: number, b: number): number;
export function canvas_to_bytes(a: number, b: number): void;
export function canvas_from_bytes(a: number, b: number, c: number): void;
export function canvas_resize(a: number, b: number, c: number): void;
export function canvas_add_dot_at(a: number, b: number, c: number, d: number): void;
export function canvas_remove_dot_at(a: number, b: number, c: number): void;
export function canvas_remap_color_palette(a: number, b: number, c: number): void;
export function canvas_get_puzzle_type(a: number, b: number): void;
export function get_color_palette(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_exn_store(a: number): void;
